CodeSystem: FXREQBusinessProcesses
Title: "Functional Requirements Business Processes"
Description:  "CodeSystem for Functional Requirements Business Processes. Autogenerated from DAK artifacts"
* ^experimental = true
* ^caseSensitive = false
* ^status = #active
* #A "Registration"
* #B "Assess and Classify the Sick Child"
* #C "Treat the child"
* #D "Referral"
* #E "Follow-up"
* #F "Aggregate Reporting"
* #G "Triage and Emergency Assessment"

